spring.application.name=vrgamesapp
server.port=${PORT:8080}
spring.datasource.url=jdbc:${MYSQL_URL}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
# Create table before propagating to the database
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Devtools
# spring.devtools.restart.enabled=true
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000
# Redis
spring.data.redis.url=${REDIS_URL}
# spring.redis.host=${REDISHOST}
# spring.redis.port=${REDISPORT}
# spring.redis.username=${REDISUSER:default}
# spring.redis.password=${REDISPASSWORD}
# Spring AI
spring.ai.google.genai.api-key=${GEMINI_KEY} 
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7
spring.ai.retry.max-attempts=1

